const PDFDocument = require("pdfkit-table");
const fs = require("fs");

const generateReport = async (userName, expenses) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 30, size: "A4" });
    const fileName = `Statement_${Date.now()}.pdf`;

    const stream = fs.createWriteStream(fileName);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).text("FinBot Monthly Statement", { align: "center" });
    doc.moveDown();
    doc.fontSize(12).text(`Name: ${userName}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.moveDown();

    //Sort Newest First
    // [...expenses] is used so that original array doesnot mutate
    const sortedExpenses = [...expenses].sort(
      (a, b) => new Date(b.date) - new Date(a.date)
    );

        // form Table Data
    const table = {
      title: "Expense Details",
      headers: ["Date", "Item", "Category", "Mode", "Amount"],
      rows: sortedExpenses.map((item) => [
        // Date format user friendly (DD/MM/YYYY)
        new Date(item.date).toLocaleDateString("en-GB"),
        item.title,
        item.category,
        item.mode,
        `Rs. ${item.amount}`,
      ]),
    };

    doc.table(table, { width: 500 });

    // Total
    const total = expenses.reduce((sum, item) => sum + item.amount, 0);
    doc.moveDown();
    doc
      .fontSize(14)
      .text(`Total Expense: Rs. ${total}`, { align: "right", color: "red" });

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(10)
      .fillColor("grey")
      .text("Generated by FinBot - Developed by Ketan", { align: "center" });

    doc.end();
    stream.on("finish", () => resolve(fileName));
    stream.on("error", (err) => reject(err));
  });
};

module.exports = { generateReport };
